### ISSUE TITLE
Change compile.py and compile_local.py to account for removal of cpbo.exe

### ISSUE THREAD

**Issue by Qerbas** [NeoArmageddon/co10_Escape#16]
The python script no longer runs when cpbo.exe is not inserted.  Inserting the file makes the script run again.  Here's the error from the console:
`Traceback (most recent call last):
  File "C:\Github Stuff\co10_Escape\compile_local_original.py", line 77, in <module>
    subprocess.call(["cpbo.exe", "-p", missiondir])
  File "C:\Programs\Python27\lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Programs\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Programs\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified`

**Comment by NeoArmageddon** [comment]
I removed cpbo.exe from the Repository due to license stuff. You can download it officially here:
http://www.armaholic.com/page.php?id=411

**Comment by marhub** [comment]
This link is no longer valid.
Also i suggest adding info about cpbo to readme.
